# Generated by Django 2.2.2 on 2019-06-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trouble',
            old_name='p_time',
            new_name='process_time',
        ),
    ]
