# Generated by Django 2.2.2 on 2019-06-15 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190615_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='nid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
