# Generated by Django 2.2.2 on 2019-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190615_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='nid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
